
#SingleInstance force
#Persistent
#Hotstring EndChars ,?!`n `t
#InputLevel, 1

:o::day.::
FormatTime, CurrentDateTime,, yyyy.MM.dd
SendInput %CurrentDateTime% `
return
:o::day_::
FormatTime, CurrentDateTime,, yyyy_MM_dd
SendInput %CurrentDateTime% `
return
:o::day::
FormatTime, CurrentDateTime,, yyyy/MM/dd
SendInput %CurrentDateTime% `
return

:o::hour::
FormatTime, CurrentDateTime,, HH:mm
SendInput %CurrentDateTime% `
return
:o::hour_::
FormatTime, CurrentDateTime,, HH_mm
SendInput %CurrentDateTime% `
return
:o::hour.::
FormatTime, CurrentDateTime,, HH.mm
SendInput %CurrentDateTime% `
return

:oC?::cad::c'est-à-dire
:oC?::Cad::C'est-à-dire
:oC?::stp::s'il te plaît
:oC?::Stp::S'il te plaît
:oC?::svp::s'il vous plaît
:oC?::Svp::S'il vous plaît
:oC?::aj::aujourd'hui
:oC?::Aj::Aujourd'hui
:oC?::we::week-end
:oC?::We::Week-end
:oC?::tfq::tu fais quoi
:oC?::Tfq::Tu fais quoi
:oC?::tkt::t'inquiète
:oC?::Tkt::T'inquiète
:oC?::rdv::rendez-vous
:oC?::Rdv::Rendez-vous
:oC?::@::qleveque@hotmail.com
:oC?::ql::Quentin LÉVÊQUE
:oC?::lev::LÉVÊQUE
:oC?::eme::ᵉ
:oC?::!!::‼
:oC?::!?::⁉
:oC?::?!::⁈
:oC?::??::⁇
:oC?::...::…
:oC?::poop::💩
:oC?::cat::😺
:oC?::fish::🐟
:oC?::pupil::🙋
:oC?::clap::👏
:oC?::pray::🙏
:oC?::muscle::💪
:oC?::note::♪
:oC?::notes::♫
:oC?::boy::♂
:oC?::girl::♀
:oC?::ok::👌
:oC?::fist::✊
:oC?::bb::👶
:oC?::cross::❎
:oC?::check::✅
:oC?::kiss::💋
:oC?::shit::🤬
:oC?::chut::🤫
:oC?::banana::🍌
:oC?::chick::🐣
:oC?::pickle::🥒
:oC?::france::🇫🇷
:oC?::nepal::🇳🇵
:oC?::teacher::👩🏼‍🏫
:oC?::clown::🤡
:oC?::vomit::🤮
:oC?::sneez::🤧
:oC?::lie::🤥
:oC?::think::🤔
:oC?::fuck::🖕
:oC?::write::✍️
:oC?::selfie::🤳
:oC?::speak::🗣️
:oC?::pregnant::🤰
:oC?::princess::👸🏻
:oC?::prince::🤴🏻
:oC?::stop::🙅‍♂️
:oC?::bomb::💣
:oC?::duck::🦆
:oC?::massage::💆🏼‍♀️
:oC?::sick::🤒
:oC?::hug::🤗
:oC?::facepalm::🤦🏻‍♂️
:oC?::wc::🚾
:oC?::burger::🍔
:oC?::crazy::🤪
:oC?::beer::🍺
:oC?::bear::🐻
:oC?::love::😍
:oC?::robot::┌( ಠ_ಠ)┘
:oC?::sir::(ಠ෴ರೃ)
:oC?::idk::¯\_(ツ)_/¯
:oC?::lenny::( ͡° ͜ʖ ͡ °)
:oC?::kind::(´• ل͜ •`)
:oC?::rip::⎧ᴿᴵᴾ⎫ ❀◟(ó ̯ ò, )
:oC?::success::(ง ͠ ͠° ل͜ °)ง
:oC?:::^)::(☉ ͜つ☉)
:oC?:::(::😦
:oC?:::|::😐
:oC?:::)::🙂
:oC?:::D::😃
:oC?:::/::😕
:oC?:::*::😗
:oC?::¦(::😞
:oC?::¦|::😑
:oC?::¦)::😏
:oC?::¦D::😄
:oC?::¦/::😒
:oC?::¦*::😚
:oC?::x(::😣
:oC?::x|::😤
:oC?::x)::😆
:oC?::xD::😂
:oC?::xP::😝
:oC?::;)::😉
:oC?::;D::😜
:oC?::;*::😘
:oC?:::o::😮
:oC?:::°::😯
:oC?:::O::😱
:oC?:::'(::😭
:oC?:::"(::😭
:oC?::>:(::😠
:oC?::3:(::👿
:oC?::3:)::😈
:oC?::B|::😎
:oC?::B)::🤓
:oC?::8)::🤓
:oC?::^^::😊
:oC?::^^'::😅
:oC?::o_o::😳
:oC?::$_$::🤑
:oC?::ê_è::🤨
:oC?:::d::😋
:oC?:::x::😶
:oC?:::s::😬
:oC?:::))::😁
:oC?:::((::😩
:oC?::0:)::😇
:oC?::(:::🙃
:oC?::D:::😧
:oC?::oplus::⊕
:oC?::otimes::⊗
:oC?::span::⟨⟩
:oC?::intint::〚,〛
:oC?::floor::⌊⌋
:oC?::ceil::⌈⌉
:oC?::nearest::⌊⌉
:oC?::abs::||
:oC?::norm::‖‖
:oC?::3sqrt::∛
:oC?::sqrt3::∛
:oC?::sqrt::√
:oC?::!para::∦
:oC?::para::∥
:oC?::!divise::∤
:oC?::!=::≠
:oC?::neq::≠
:oC?::!eq::≠
:oC?::empty::ø
:oC?:::=::≔
:oC?::div::÷
:oC?::leq::≤
:oC?::geq::≥
:oC?::forall::∀
:oC?::mapsto::↦
:oC?::<=>::⇔
:oC?::=>::⇒
:oC?::<=::⇐
:oC?::iff::⇔
:oC?::injection::↪
:oC?::surjection::↠
:oC?::half::½
:oC?::times::×
:oC?::!exists::∄
:oC?::exists::∃
:oC?::perp::⊥
:oC?::sum::∑
:oC?::prod::∏
:oC?::scup::∐
:oC?::cap::⋂
:oC?::cup::⋃
:oC?::!subset::⊄
:oC?::!subseteq::⊈
:oC?::subset::⊂
:oC?::supset::⊃
:oC?::subseteq::⊆
:oC?::supseteq::⊇
:oC?::<<::≪
:oC?::>>::≫
:oC?::!prec::⊀
:oC?::!succ::⊁
:oC?::prec::≺
:oC?::succ::≻
:oC?::!in::∉
:oC?::in::∈
:oC?::ni::∋
:oC?::int::∫
:oC?::del::∂
:oC?::infty::∞
:oC?::propto::∝
:oC?::contradiction::↯
:oC?::pm::±
:oC?::mp::∓
:oC?::circ::∘
:oC?::simeq::≃
:oC?::?=::≟
:oC?::equiv::≡
:oC?::mod::≡
:oC?::cqfd::▨
:oC?::langle::⟨
:oC?::rangle::⟩
:oC?::f::ƒ
:oC?::exp::ℯ
:oC?::'''::‴
:oC?::''::″
:oC?::'::′
:oC?::alpha::α
:oC?::beta::β
:oC?::gamma::γ
:oC?::delta::δ
:oC?::varepsilon::ϵ
:oC?::epsilon::ε
:oC?::zeta::ζ
:oC?::eta::η
:oC?::vartheta::ϑ
:oC?::theta::θ
:oC?::iota::ι
:oC?::varkappa::ϰ
:oC?::kappa::κ
:oC?::lambda::λ
:oC?::mu::μ
:oC?::nu::ν
:oC?::xi::ξ
:oC?::omicron::ο
:oC?::varpi::ϖ
:oC?::pi::π
:oC?::rho::ρ
:oC?::sigma::σ
:oC?::tau::τ
:oC?::upsilon::υ
:oC?::varphi::ϕ
:oC?::phi::φ
:oC?::chi::χ
:oC?::psi::ψ
:oC?::omega::ω
:oC?::Alpha::Α
:oC?::Beta::Β
:oC?::Gamma::Γ
:oC?::Delta::Δ
:oC?::Epsilon::Ε
:oC?::Zeta::Ζ
:oC?::Eta::Η
:oC?::Theta::Θ
:oC?::Iota::Ι
:oC?::Kappa::Κ
:oC?::Lambda::Λ
:oC?::Mu::Μ
:oC?::Nu::Ν
:oC?::Xi::Ξ
:oC?::Omicron::Ο
:oC?::Pi::Π
:oC?::Rho::Ρ
:oC?::Sigma::Σ
:oC?::Tau::Τ
:oC?::Upsilon::Υ
:oC?::Phi::Φ
:oC?::Chi::Χ
:oC?::Psi::Ψ
:oC?::Omega::Ω
:oC?::nabla::∇
:oC?::vect::{U+20D7}
:oC?::bar::{U+0304}
:oC?::underline::{U+0332}
:oC?::hat::{U+0302}
:oC?::circle::{U+030A}
:oC?::ldots::…
:oC?::cdot::·
:oC?::dot::•
:oC?::cdots::⋯
:oC?::vdots::⋮
:oC?::ccall::𝕮
:oC?::acall::𝕬
:oC?::dcall::𝕯
:oC?::mcall::𝕸
:oC?::xcall::𝖃
:oC?::acal::𝒜
:oC?::ccal::ℭ
:oC?::mcal::ℳ
:oC?::bcal::ℬ
:oC?::ical::ℐ
:oC?::tcal::𝓣
:oC?::pcal::℘
:oC?::lcal::ℒ
:oC?::ncal::𝒩
:oC?::qset::ℚ
:oC?::rset::ℝ
:oC?::zset::ℤ
:oC?::pset::ℙ
:oC?::nset::ℕ
:oC?::cset::ℂ
:oC?::eset::𝔼
:oC?::hset::ℍ
:oC?::uset::𝕌
:oC?::kset::𝕂
:oC?::iset::𝕀
:oC?::1set::𝟙
:oC?::^n::ⁿ
:oC?::^1::¹
:oC?::^2::²
:oC?::^3::³
:oC?::^4::⁴
:oC?::^5::⁵
:oC?::^6::⁶
:oC?::^7::⁷
:oC?::^8::⁸
:oC?::^9::⁹
:oC?::^0::⁰ 
:oC?::^(::⁽⁾{left}
:oC?::^+::⁺
:oC?::^-::⁻
:oC?::^c::ᶜ
:oC?::^m::ᵐ
:oC?::^o::ᵒ
:oC?::^r::ʳ
:oC?::^x::ˣ
:oC?::^i::ⁱ
:oC?::inv::⁻¹
:oC?::_1::₁
:oC?::_2::₂
:oC?::_3::₃
:oC?::_4::₄
:oC?::_5::₅
:oC?::_6::₆
:oC?::_7::₇
:oC?::_8::₈
:oC?::_9::₉
:oC?::_0::₀
:oC?::_(::₍₎{left}
:oC?::_+::₊
:oC?::_-::₋
:oC?::_a::ₐ
:oC?::_i::ᵢ
:oC?::_j::ⱼ
:oC?::_m::ₘ
:oC?::_n::ₙ
:oC?::right::→
:oC?::left::←
:oC?::up::↑
:oC?::down::↓
:oC?::prouve::╟
:oC?::semantique::╞
:oC?::syntaxique::├
:oC?::equipotent::≈
:oC?::andl::∧
:oC?::orl::∨
:oC?::eql::↔
:oC?::cong::≅
:oC?::subgroup::⊲
:oC?::conv::∗
:oC?::nol::¬
:oC?::matrix::┌┐\n||\n└┘
:oC?:i:maps::https://www.google.ch/maps
:oC?:i:koreus::http://www.koreus.com/modules/news/
:oC?:i:tff::http://10fastfingers.com/typing-test/french
:oC?:i:hordes::http://www.hordes.fr
:oC?:i:fb::http://www.facebook.com
:oC?:i:twitch::http://www.twitch.tv/directory/following
:oC?:i:quotidien::http://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos
:oC?:i:shinobi::http://www.shinobi.fr/
:oC?:i:labrute::http://labrute.muxxu.com
:oC?:i:isa::https://isa.epfl.ch/imoniteur_ISAP/PORTAL14S.htm
:oC?:i:libgen::http://gen.lib.rus.ec/
:oC?:i:moodle::http://moodle.epfl.ch/
:oC?:i:cff::http://www.cff.ch/horaire.html
:oC?:i:blablacar::https://www.blablacar.fr/
:oC?:i:jvc::http://www.jeuxvideo.com/
:oC?:i:cic::https://www.cic.fr/cio-bro/fr/index.html
:oC?:i:bcv::https://www.bcv.ch/bcvd-login/authenticateAction.do
:oC?:i:zoelise::https://zoeliseblog.wordpress.com/
:oC?:i:chess::http://lichess.org
:oC?:i:cookie::http://orteil.dashnet.org/cookieclicker/
:oC?:i:insta::https://www.instagram.com/
:oC?:i:pirate::https://proxybay.bz
:oC?:i:msg::https://www.messenger.com
:oC?:i:wa::http://web.whatsapp.com
:oC?:i:salt::http://www.salt.ch/fr/myaccount/
:oC?:i:li::http://www.linkedin.com/in/quentin-leveque/
:oC?:i:y::http://www.youtube.com/feed/subscriptions
:oC?:i:qleveque::http://qleveque.fr
:oC?:i:sr::http://www.speedrun.com
:oC?:i:oot::http://www.speedrun.com/oot
:oC?:i:sm64::http://www.speedrun.com/sm64
:oC?:i:fsymbols::http://fsymbols.com/fr/
:oC?:i:igg::http://igg-games.com
:oC?:i:anibis::http://www.anibis.ch/fr/default.aspx
:oC?:i:itch::http://itch.io
:oC?:i:t::http://twitter.com/
:oC?:i:wiki::https://fr.wikipedia.org/wiki/Wikipédia:Accueil_principal
:oC?:i:deepl::http://www.deepl.com/translator
:oC?:i:discord::http://discordapp.com/channels/@me
:oC?:i:ej::http://www.easyjet.com/ch-fr
:oC?:i:ta::http://www.tripadvisor.fr
:oC?:i:reddit::http://www.reddit.com
:oC?:i:ahk_forum::http://autohotkey.com/boards/
:oC?:i:9gag::http://9gag.com
:oC?:i:db::https://www.dropbox.com/
:oC?:i:zalando::https://fr.zalando.ch/accueil-homme/
:oC?:i:subtitles::https://www.yifysubtitles.com/movie-imdb/tt1396484
:oC?:i:sfr_mail::https://webmail.sfr.fr/fr_FR/main.html#welcome
:oC?:i:button::https://www.kongregate.com/games/truefire/press-the-button
:oC?:i:ali::https://fr.aliexpress.com
:oC?:i:capitales::https://www.jetpunk.com/user-quizzes/29612/capitales-du-monde
:oC?:i:pays::https://www.jetpunk.com/quizzes/pays-du-monde
:oC?:i:departements::https://www.jetpunk.com/user-quizzes/71167/departements-francais
:oC?:i:prefectures::https://www.jetpunk.com/user-quizzes/111275/chefs-lieux-des-departements-francais
:oC?:i:arbres::www.snv.jussieu.fr/bmedia/arbres/identification-feuilles.htm
:oC?:i:fleurs::https://fr.teleflora.com/floral-facts/glossary-of-flowers
:oC?:i:meme::https://imgflip.com/memegenerator
:oC?:i:ctr::http://ctr4ever.joora.fr/home.php
:oC?:i:github::https://github.com/
:oC?:i:repeat::https://listenonrepeat.com
:oC?:i:indeed::https://my.indeed.com
:oC?:i:jobs::https://www.jobs.ch
:oC?:i:voc::https://www.vocabulary.cl/Lists.htm
:oC?:i:i::https://www.google.com/imghp
:oC?:v:bcv_iban::CH62 00767 000E 5337 4044
:oC?:v:bcv_bic::BCVLCH2LXX
:oC?:v:cic_iban::FR76 3004 7140 5800 0205 5150 173
:oC?:v:cic_rib::30047 14058 00020551501 73
:oC?:v:tel::078 645 01 29
:oC?:v:tel_f::06 58 92 55 65
:oC?:v:home::av. de l'Eglise Anglaise, 12, Studio 1110
:oC?:v:city::1006 Lausanne
:oC?:v:home_f::5, rue de Silguy
:oC?:v:city_f::29000 Quimper
:oC?:v:voyageur::29090109656553483
:oC?:v:pin::0846
:oC?:v:puk::05546626
:oC?:v:pin2::9634
:oC?:v:puk2::94226178
:oC?:v:bcv::h9824106
:oC?:v:cic::400514508994
:oC?:v:wifi::a7vy-gzj3-ztdw-xsnn
:oC?:v:wifi_f::5AE69A3A3EA3EA05EA55F872C3
:oC?:v:mediathèque::134636
:oC?:a:rm::del
:oC?:a:vimy::call "C:\Program Files (x86)\Vim\vim81\vim.exe" -y
:oC?:a:less::"C:\Program Files (x86)\Vim\vim81\vim.exe" --cmd "let no_plugin_maps = 1" -c "runtime! macros/less.vim"
:oC?:a:touch::copy NUL
:oC?:a:mv::move
:oC?:a:ls::dir
:oC?:a:grep::findstr
:oC?:a:cp::xcopy
:oC?:a:clear::cls
:oC?:a:chrome::start "" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
:oC?:a:e::start "" "C:\Program Files (x86)\Notepad++\notepad++.exe"
:oC?:c:docs::C:\Users\Whenti\Documents
:oC?:c:pyq::C:\Users\Whenti\Documents\Macros\pyq
:oC?:c:qey::C:\Users\Whenti\Documents\Macros\qey
:oC?:c:db::C:\Users\Whenti\Dropbox
:oC?:f:test::C:\Users\Whenti\Dropbox\pyq\python\je suis.txt
