
#SingleInstance force
#Persistent
#Hotstring EndChars ,?!`n `t
#InputLevel, 1

:o?::day::
FormatTime, CurrentDateTime,, yyyy/MM/dd
SendInput %CurrentDateTime%
return

:o?::hour::
FormatTime, CurrentDateTime,, HH:mm
SendInput %CurrentDateTime%
return

:o?::time::
FormatTime, CurrentDateTime,, yyyy-MM-dd_HH-mm-ss
SendInput %CurrentDateTime%
return

:oC?::underline::{U+0332}
:oC?::bcal::ℬ
:oC?::^m::ᵐ
:oC?:d:docs::C:/Users/qleveque/Documents/.
:oC?:::°::😯
:oC?::8)::🤓
:oC?:d:bb::C:/Users/qleveque/Documents/codes/BlueBotics/.
:oC?::eql::↔
:oC?::>:(::😠
:oC?::banana::🍌
:oC?::_3::₃
:oC?:d:c::C:\.
:oC?::acall::𝕬
:oC?::_m::ₘ
:oC?::cset::ℂ
:oC?::neq::≠
:oC?:i:releases::http://bluedev/builds/official/buildInfo.html
:oC?::subgroup::⊲
:oC?::rip::⎧ᴿᴵᴾ⎫ ❀◟(ó ̯ ò, )
:oC?::Chi::Χ
:oC?::infty::∞
:oC?::semantique::╞
:oC?::!!::‼
:oC?::vect::{U+20D7}
:oC?::Alpha::Α
:oC?::success::(ง ͠ ͠° ل͜ °)ง
:oC?:::=::≔
:oC?:d:i::i:\.
:oC?::^^::😊
:oC?::prod::∏
:oC?::cdots::⋯
:oC?::down::↓
:oC?::rho::ρ
:oC?::boy::♂
:oC?::cup::⋃
:oC?::_4::₄
:oC?::sqrt::√
:oC?::^c::ᶜ
:oC?::o_o::😳
:oC?:f:todo::C:/Users/qleveque/Documents/papers/todo.txt
:oC?::kiss::💋
:oC?::lev::LÉVÊQUE
:oC?::langle::⟨
:oC?::shit::🤬
:oC?:i:antlab::https://bluebotics.atlassian.net/wiki/spaces/ANT/pages/640745476/ANTlab+-+Design+doc
:oC?::_6::₆
:oC?::_+::₊
:oC?:d:options::C:\Users\qleveque\Documents\options\.
:oC?::gamma::γ
:oC?::pm::±
:oC?:f:voc::C:\Users\qleveque\Documents\papers\voc.txt
:oC?::1set::𝟙
:oC?::nabla::∇
:oC?::Kappa::Κ
:oC?::Rho::Ρ
:oC?::kset::𝕂
:oC?::Zeta::Ζ
:oC?::think::🤔
:oC?::times::×
:oC?:i:server::http://127.0.0.1:8081/wms/monitor/index.html#login
:oC?:i:confluence::https://bluebotics.atlassian.net
:oC?::psi::ψ
:oC?::chut::🤫
:oC?::^4::⁴
:oC?::mapsto::↦
:oC?::Pi::Π
:oC?::B)::🤓
:oC?::!eq::≠
:oC?::propto::∝
:oC?::cqfd::▨
:oC?::xi::ξ
:oC?::^i::ⁱ
:oC?::¦*::😚
:oC?::<<::≪
:oC?:f:hours::C:\Users\qleveque\Documents\papers\hours.txt
:oC?::equiv::≡
:oC?::Iota::Ι
:oC?::^6::⁶
:oC?::Tau::Τ
:oC?::cap::⋂
:oC?::tfq::tu fais quoi
:oC?::syntaxique::├
:oC?::iff::⇔
:oC?::muscle::💪
:oC?::prec::≺
:oC?::rset::ℝ
:oC?::pray::🙏
:oC?::in::∈
:oC?::Eta::Η
:oC?::nepal::🇳🇵
:oC?::forall::∀
:oC?::Epsilon::Ε
:oC?:v:ip_getaway::192.168.9.x
:oC?:d:prog::C:/Program Files
:oC?::^1::¹
:oC?::kappa::κ
:oC?::¦(::😞
:oC?::Cad::C'est-à-dire
:oC?:d:j::J:\.
:oC?::pi::π
:oC?::span::⟨⟩
:oC?:::"(::😭
:oC?::princess::👸🏻
:oC?::;D::😜
:oC?::!prec::⊀
:oC?:::^)::(☉ ͜つ☉)
:oC?::mcal::ℳ
:oC?::Beta::Β
:oC?::Mu::Μ
:oC?::^2::²
:oC?::subset::⊂
:oC?::tcal::𝓣
:oC?::!in::∉
:oC?::note::♪
:oC?::idk::¯\_(ツ)_/¯
:oC?::phi::φ
:oC?:::d::😋
:oC?:d:tmp::T:\.
:oC?::varepsilon::ϵ
:oC?::orl::∨
:oC?::lenny::( ͡° ͜ʖ ͡ °)
:oC?::beta::β
:oC?::Stp::S'il te plaît
:oC?::Sigma::Σ
:oC?::=>::⇒
:oC?::pset::ℙ
:oC?::0:)::😇
:oC?::¦)::😏
:oC?::<=>::⇔
:oC?::cdot::·
:oC?:::|::😐
:oC?::pupil::🙋
:oC?::svp::s'il vous plaît
:oC?::omicron::ο
:oC?::selfie::🤳
:oC?::B|::😎
:oC?::ical::ℐ
:oC?::!subseteq::⊈
:oC?::up::↑
:oC?:i:wiki::https://bluebotics.atlassian.net
:oC?::uset::𝕌
:oC?::norm::‖‖
:oC?::scup::∐
:oC?::clown::🤡
:oC?::xcall::𝖃
:oC?::Theta::Θ
:oC?:v:ip::192.168.8.82
:oC?::cad::c'est-à-dire
:oC?::eta::η
:oC?::eset::𝔼
:oC?::left::←
:oC?::poop::💩
:oC?::teacher::👩🏼‍🏫
:oC?::nset::ℕ
:oC?::nearest::⌊⌉
:oC?::^-::⁻
:oC?::ccal::ℭ
:oC?::x(::😣
:oC?::!=::≠
:oC?:d:h::H:\.
:oC?::sick::🤒
:oC?:d:progx::C:/Program Files (x86)
:oC?::matrix::┌┐\n||\n└┘
:oC?:::'(::😭
:oC?::_(::₍₎{left}
:oC?::acal::𝒜
:oC?:d:macros::C:/Users/qleveque/Documents/macros/.
:oC?::fist::✊
:oC?::sum::∑
:oC?::omega::ω
:oC?::perp::⊥
:oC?::contradiction::↯
:oC?::sigma::σ
:oC?::'::′
:oC?::ldots::…
:oC?:i:hours::http://bluedev/timetracker
:oC?:::O::😱
:oC?::stp::s'il te plaît
:oC?::injection::↪
:oC?::ceil::⌈⌉
:oC?::empty::ø
:oC?::xD::😂
:oC?:i:gerrit::http://bluedev:8086/dashboard/self
:oC?::^r::ʳ
:oC?::nu::ν
:oC?::ok::👌
:oC?::exp::ℯ
:oC?::duck::🦆
:oC?::prince::🤴🏻
:oC?::alpha::α
:oC?::half::½
:oC?:v:ip_robots::192.168.8.x
:oC?::^n::ⁿ
:oC?::notes::♫
:oC?::france::🇫🇷
:oC?:::x::😶
:oC?::bb::👶
:oC?::clap::👏
:oC?::We::Week-end
:oC?:::((::😩
:oC?::andl::∧
:oC?::Tfq::Tu fais quoi
:oC?::leq::≤
:oC?:d:papers::C:/Users/qleveque/Documents/papers/.
:oC?::!succ::⊁
:oC?::iota::ι
:oC?:v:ip_laser::192.168.0.[12]
:oC?::Gamma::Γ
:oC?::?!::⁈
:oC?::mcall::𝕸
:oC?::we::week-end
:oC?::3:)::😈
:oC?::^x::ˣ
:oC?::?=::≟
:oC?::lie::🤥
:oC?::_j::ⱼ
:oC?::cat::😺
:oC?::geq::≥
:oC?::_i::ᵢ
:oC?::(:::🙃
:oC?:::D::😃
:oC?::intint::〚,〛
:oC?::tau::τ
:oC?:::(::😦
:oC?::^0::⁰ 
:oC?::varkappa::ϰ
:oC?::delta::δ
:oC?::_0::₀
:oC?::vartheta::ϑ
:oC?::...::…
:oC?::!para::∦
:oC?::tkt::t'inquiète
:oC?::abs::||
:oC?::zeta::ζ
:oC?::kind::(´• ل͜ •`)
:oC?::facepalm::🤦🏻‍♂️
:oC?::supseteq::⊇
:oC?::Delta::Δ
:oC?::succ::≻
:oC?::varphi::ϕ
:oC?::^+::⁺
:oC?::Lambda::Λ
:oC?:::))::😁
:oC?::Phi::Φ
:oC?::ni::∋
:oC?::check::✅
:oC?::oplus::⊕
:oC?::exists::∃
:oC?::;)::😉
:oC?::lcal::ℒ
:oC?::qset::ℚ
:oC?::¦|::😑
:oC?:i:robots::https://bluebotics.atlassian.net/wiki/spaces/ANT/pages/31326301/Platform+network
:oC?::fuck::🖕
:oC?::bear::🐻
:oC?:i:owncloud::http://bluedev/owncloud/
:oC?::del::∂
:oC?::circ::∘
:oC?:d:p::P:\.
:oC?::xP::😝
:oC?::Omega::Ω
:oC?::mod::≡
:oC?::'''::‴
:oC?::ê_è::🤨
:oC?::speak::🗣️
:oC?::^(::⁽⁾{left}
:oC?::prouve::╟
:oC?::f::ƒ
:oC?::hat::{U+0302}
:oC?::_n::ₙ
:oC?::_7::₇
:oC?:i:all::http://bluedev/
:oC?::ccall::𝕮
:oC?::vomit::🤮
:oC?::conv::∗
:oC?::ql::Quentin LÉVÊQUE
:oC?::^9::⁹
:oC?::Tkt::T'inquiète
:oC?::pcal::℘
:oC?:d:mybin::C:/Users/qleveque/Documents/macros/mybin/.
:oC?:f:recap::C:/Users/qleveque/Documents/papers/recap.txt
:oC?::_-::₋
:oC?::;*::😘
:oC?::sneez::🤧
:oC?:i:jenkins::http://bluedev:8080/
:oC?::nol::¬
:oC?::!exists::∄
:oC?::chi::χ
:oC?::<=::⇐
:oC?::!?::⁉
:oC?::surjection::↠
:oC?::^^'::😅
:oC?::chick::🐣
:oC?::^o::ᵒ
:oC?::$_$::🤑
:oC?::^5::⁵
:oC?::otimes::⊗
:oC?:f:notes::C:/Users/qleveque/Documents/papers/notes.txt
:oC?::massage::💆🏼‍♀️
:oC?:::/::😕
:oC?::x|::😤
:oC?::love::😍
:oC?::upsilon::υ
:oC?::girl::♀
:oC?::_1::₁
:oC?::!divise::∤
:oC?::int::∫
:oC?::rangle::⟩
:oC?::3:(::👿
:oC?::^3::³
:oC?::_a::ₐ
:oC?::mp::∓
:oC?::bomb::💣
:oC?::¦/::😒
:oC?::!subset::⊄
:oC?::subseteq::⊆
:oC?::supset::⊃
:oC?::simeq::≃
:oC?::fish::🐟
:oC?::div::÷
:oC?::x)::😆
:oC?::wc::🚾
:oC?::varpi::ϖ
:oC?::D:::😧
:oC?::Upsilon::Υ
:oC?::Omicron::Ο
:oC?::''::″
:oC?:i:ips::https://bluebotics.atlassian.net/wiki/spaces/ANT/pages/516358175/IP+addresses+for+computers+at+BlueBotics
:oC?::vdots::⋮
:oC?::aj::aujourd'hui
:oC?:d:wms::C:\Users\qleveque\Documents\codes\BlueBotics\App\WMS\wms\.
:oC?::pickle::🥒
:oC?::_9::₉
:oC?::write::✍️
:oC?::burger::🍔
:oC?::circle::{U+030A}
:oC?::zset::ℤ
:oC?::hset::ℍ
:oC?:d:projects::C:\Users\qleveque\Documents\codes\BlueBotics\Tools\AutoTests_java\projects
:oC?::_5::₅
:oC?::theta::θ
:oC?::rdv::rendez-vous
:oC?::floor::⌊⌋
:oC?::¦D::😄
:oC?::^7::⁷
:oC?::lambda::λ
:oC?::@::qleveque@hotmail.com
:oC?:d:antlab::C:\Users\qleveque\Documents\codes\BlueBotics\App\ANTlab\.
:oC?::_8::₈
:oC?:v:softbook::practical handbook of software construction
:oC?::inv::⁻¹
:oC?:::s::😬
:oC?::Aj::Aujourd'hui
:oC?::Nu::Ν
:oC?::cross::❎
:oC?::mu::μ
:oC?::stop::🙅‍♂️
:oC?::beer::🍺
:oC?:d:api::I:\Products\ANT server\4 Service\Manual\.
:oC?::bar::{U+0304}
:oC?::3sqrt::∛
:oC?::right::→
:oC?::_2::₂
:oC?::robot::┌( ಠ_ಠ)┘
:oC?::Psi::Ψ
:oC?::hug::🤗
:oC?::crazy::🤪
:oC?::Rdv::Rendez-vous
:oC?:::o::😮
:oC?::ncal::𝒩
:oC?::??::⁇
:oC?::sqrt3::∛
:oC?::cong::≅
:oC?:f:antlab::C:\Users\qleveque\Documents\papers\antlab.txt
:oC?::Xi::Ξ
:oC?:i:mail::https://workspace.infomaniak.com
:oC?::epsilon::ε
:oC?::eme::ᵉ
:oC?::dcall::𝕯
:oC?:i:antserver::https://bluebotics.atlassian.net/wiki/spaces/ANT/pages/37734664/Installation+of+ANT+server+s+development+environment
:oC?:::)::🙂
:oC?::>>::≫
:oC?::para::∥
:oC?::pregnant::🤰
:oC?::dot::•
:oC?:::*::😗
:oC?::^8::⁸
:oC?:i:jira::https://bluebotics.atlassian.net/secure/Dashboard.jspa
:oC?::equipotent::≈
:oC?::iset::𝕀
:oC?::Svp::S'il vous plaît
:oC?::sir::(ಠ෴ರೃ)
